// The 16 divisions Atlas XI tracks, with hand-set league-strength coefficients (PLAN.md §3).
// Ordered by coefficient (strongest first). Coefficients are v1 starters and tunable.
const LEAGUES = [
  {
    id: "eng-1",
    name: "Premier League",
    country: "England",
    countryCode: "ENG",
    tier: 1,
    coefficient: 1.0,
  },
  {
    id: "esp-1",
    name: "La Liga",
    country: "Spain",
    countryCode: "ESP",
    tier: 1,
    coefficient: 0.95,
  },
  {
    id: "ger-1",
    name: "Bundesliga",
    country: "Germany",
    countryCode: "GER",
    tier: 1,
    coefficient: 0.92,
  },
  {
    id: "ita-1",
    name: "Serie A",
    country: "Italy",
    countryCode: "ITA",
    tier: 1,
    coefficient: 0.92,
  },
  {
    id: "fra-1",
    name: "Ligue 1",
    country: "France",
    countryCode: "FRA",
    tier: 1,
    coefficient: 0.85,
  },
  {
    id: "por-1",
    name: "Primeira Liga",
    country: "Portugal",
    countryCode: "POR",
    tier: 1,
    coefficient: 0.78,
  },
  {
    id: "ned-1",
    name: "Eredivisie",
    country: "Netherlands",
    countryCode: "NED",
    tier: 1,
    coefficient: 0.75,
  },
  {
    id: "bel-1",
    name: "Pro League",
    country: "Belgium",
    countryCode: "BEL",
    tier: 1,
    coefficient: 0.72,
  },
  {
    id: "eng-2",
    name: "Championship",
    country: "England",
    countryCode: "ENG",
    tier: 2,
    coefficient: 0.66,
  },
  {
    id: "ger-2",
    name: "2. Bundesliga",
    country: "Germany",
    countryCode: "GER",
    tier: 2,
    coefficient: 0.62,
  },
  { id: "ita-2", name: "Serie B", country: "Italy", countryCode: "ITA", tier: 2, coefficient: 0.6 },
  {
    id: "esp-2",
    name: "Segunda División",
    country: "Spain",
    countryCode: "ESP",
    tier: 2,
    coefficient: 0.6,
  },
  {
    id: "fra-2",
    name: "Ligue 2",
    country: "France",
    countryCode: "FRA",
    tier: 2,
    coefficient: 0.58,
  },
  {
    id: "sco-1",
    name: "Scottish Premiership",
    country: "Scotland",
    countryCode: "SCO",
    tier: 1,
    coefficient: 0.55,
  },
  {
    id: "mar-1",
    name: "Botola Pro 1",
    country: "Morocco",
    countryCode: "MAR",
    tier: 1,
    coefficient: 0.5,
  },
  {
    id: "ned-2",
    name: "Eerste Divisie",
    country: "Netherlands",
    countryCode: "NED",
    tier: 2,
    coefficient: 0.48,
  },
];

module.exports = { LEAGUES };
